### PR TITLE
Add Logo to Partners Section

### PR DESCRIPTION
**Pull request by nerdlet**
## Description

Fixes # 171691895

## Type of change
- [x] New feature (non-breaking change which adds functionality)

### Screenshots
Screenshot 2020-03-10 at 13 06 59

Screenshot 2020-03-10 at 13 06 32

Screenshot 2020-03-10 at 12 59 06

Screenshot 2020-03-10 at 13 07 19

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by chegejames** [comment]
Hey @nerdlet thanks for pulling this together quickly. 

Have you checked the grid alignment especially "large device screen" it looks a little off to the naked eye.

I also have been meaning to mention mobile optimisation as the current "mobile version" of the site is similar to the desktop one. From analytics, looks as though people on mobile have very high drop-off rates. Could this be the issue?

**Comment by nerdlet** [comment]
@chegejames Looking into it. Also, I think we can handle the mobile optimization with the conversion to next.js

**Comment by nerdlet** [comment]
@chegejames Ping on the links to partner site

**Comment by chegejames** [comment]
@nerdlet Now you are bringing it! Awesome!

**Pull request merged**
